version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vitaluxe-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vitaluxe
    ports:
      - "3306:3306"
    volumes:
      - vitaluxe-mysql-data:/var/lib/mysql

volumes:
  vitaluxe-mysql-data:
